{"uuid": "2a4fb2ae-ff64-49b5-a704-2ef19e5ed253", "children": ["c58f5eb7-7bbd-415c-9a5f-c8c5fb960522", "a156f029-09d5-4b2a-83df-c1c53c26550a"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=88.0.4324.150)\nStacktrace:\n0   chromedriver                        0x0000000105e58e09 chromedriver + 2641417\n1   chromedriver                        0x00000001064e44b3 chromedriver + 9503923\n2   chromedriver                        0x0000000105bfb9b3 chromedriver + 162227\n3   chromedriver                        0x0000000105be02df chromedriver + 49887\n4   chromedriver                        0x0000000105c49cc9 chromedriver + 482505\n5   chromedriver                        0x0000000105c55ee2 chromedriver + 532194\n6   chromedriver                        0x0000000105c47553 chromedriver + 472403\n7   chromedriver                        0x0000000105c21ae4 chromedriver + 318180\n8   chromedriver                        0x0000000105c22a87 chromedriver + 322183\n9   chromedriver                        0x0000000105e28ab9 chromedriver + 2443961\n10  chromedriver                        0x0000000105e3589f chromedriver + 2496671\n11  chromedriver                        0x0000000105e3555b chromedriver + 2495835\n12  chromedriver                        0x0000000105e0f4c5 chromedriver + 2340037\n13  chromedriver                        0x0000000105e3647f chromedriver + 2499711\n14  chromedriver                        0x0000000105e1e049 chromedriver + 2400329\n15  chromedriver                        0x0000000105e4d33f chromedriver + 2593599\n16  chromedriver                        0x0000000105e5e523 chromedriver + 2663715\n17  libsystem_pthread.dylib             0x00007fff6f522109 _pthread_start + 148\n18  libsystem_pthread.dylib             0x00007fff6f51db8b thread_start + 15\n\n", "trace": "  File \"/Library/Python/3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Python/3.8/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Python/3.8/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/akshaykalyanashetti/Downloads/Sel_frm_scarth2-master/conftest.py\", line 10, in test_setup\n    driver.maximize_window()\n  File \"/Library/Python/3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 821, in maximize_window\n    self.execute(command, params)\n  File \"/Library/Python/3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 338, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Python/3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 240, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1613479549158, "stop": 1613479555896}], "start": 1613479549158, "stop": 1613479556323}